namespace interpreter.Utils
{
    class Keywords
    {
        public static readonly IReadOnlyDictionary<string, byte> list = new Dictionary<string, byte>
        {
            ["ADD"] = Opcodes.ADD,
            ["ADDRESS"] = Core.Interpreter.REG_RAM_ADDRESS,
            ["AND"] = Opcodes.AND,
            ["ASHR"] = Opcodes.ASHR,
            ["CALL"] = 210,
            ["CLEAR"] = Opcodes.CLEAR,
            ["COPY_CONST"] = 192,
            ["COUNTER"] = 6,
            ["DIV"] = Opcodes.DIV,
            ["GOTO"] = 208,
            ["HALT"] = Opcodes.HALT,
            ["IF_EQL"] = Opcodes.IF_EQL,
            ["IF_GOE"] = Opcodes.IF_GOE,
            ["IF_GRT"] = Opcodes.IF_GRT,
            ["IF_LES"] = Opcodes.IF_LES,
            ["IF_LOE"] = Opcodes.IF_LOE,
            ["IF_NEQ"] = Opcodes.IF_NEQ,
            ["IN"] = 1,
            ["INPUT"] = 9,
            ["INPUT_RAM"] = 11,
            ["MOD"] = Opcodes.MOD,
            ["MOV"] = 64,
            ["MULTIPLY"] = Opcodes.MULTIPLY,
            ["NEXT"] = 64,
            ["NOT_A"] = Opcodes.NOT_A,
            ["OR"] = Opcodes.OR,
            ["OUTPUT"] = 7,
            ["PREVIOUS"] = 65,
            ["PRINT"] = 64,
            ["RAM"] = 10,
            ["REG0"] = 0,
            ["REG1"] = 1,
            ["REG2"] = 2,
            ["REG3"] = 3,
            ["REG4"] = 4,
            ["REG5"] = 5,
            ["RETURN"] = 64,
            ["ROL"] = Opcodes.ROL,
            ["ROR"] = Opcodes.ROR,
            ["SHL"] = Opcodes.SHL,
            ["SHR"] = Opcodes.SHR,
            ["STACK"] = 8,
            ["SUB"] = Opcodes.SUB,
            ["TO"] = 0,
            ["WAIT"] = Opcodes.WAIT,
            ["XOR"] = Opcodes.XOR
        };
    }
}